spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:SpringCloudify/config-repo-demo.git
          username: yunsu2
          password: san.1415926
server:
  port: 1201

